//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasMedicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int idCita { get; set; }
        public string NombreCita { get; set; }
        public string NombrePaciente { get; set; }
        public System.DateTime FechaCita { get; set; }
        public decimal PrecioCita { get; set; }
        public string NombreDoctor { get; set; }
    }
}
